print("harry potter")
print("harry potter is a wizard")
print("harry potter is a student at hogwarts")
print("harry potter has a scar on his forehead")
print("harry potter has a pet owl named hedwig")
print("harry potter has a best friend named ron weasley")
print("harry potter has a best friend named hermione granger")
print("harry potter has a nemesis named lord voldemort")
print("harry potter is brave")
print("harry potter is loyal")
print("harry potter is a hero")